name: Build LaTeX PDF

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  MAIN_TEX: main.tex  # si tu archivo principal cambia, ajústalo aquí

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-spanish \
            latexmk

      # BibTeX clásico (sin -use-biber y sin -shell-escape)
      - name: Compile PDF (latexmk + BibTeX)
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error "$MAIN_TEX"

      - name: Upload PDF
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: memoria-pdf
          path: ${MAIN_TEX%.tex}.pdf
