name: Build LaTeX PDF

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  MAIN_TEX: main.tex  # cámbialo a tu archivo principal (p. ej., memoria.tex)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-spanish \
            biber \
            latexmk

      - name: Compile PDF (latexmk + biber)
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error -use-biber "$MAIN_TEX"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: memoria-pdf
          path: |
            ${MAIN_TEX%.tex}.pdf

